import json

knowledge_points = [
    {
        "id": "s1-kp-001",
        "title": "Se lever avec empressement pour servir Hachem",
        "rule": "Il faut se lever avec courage et empressement pour accomplir les Mitsvot, en particulier pour commencer sa journée au service de Hachem.",
        "explanation": "L'empressement ne consiste pas à courir parce que l'on s'est réveillé trop tard. Il faut au contraire s'habituer à se lever suffisamment tôt afin d'accomplir les Mitsvot à temps.",
        "practical_example": "Une personne reste au lit jusqu'à la dernière minute puis court vers la synagogue. Le fait de courir ne correspond pas à l'empressement recherché par le Siman.",
        "common_trap": "Confondre rapidité et empressement : arriver en courant après s'être levé tard n'est pas l'idéal décrit ici.",
        "importance": "essential",
        "frequency": "common",
        "learning_level": 1,
        "knowledge_type": "principle",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 1}, {"siman": 1, "seif": 2}],
        "concepts": ["זריזות", "השכמת הבוקר", "תפילה"]
    },
    {
        "id": "s1-kp-002",
        "title": "Temps de sommeil recommandé",
        "rule": "Un homme ne doit pas dormir moins de six heures ni plus de huit heures.",
        "explanation": "Le sommeil excessif nuit à la santé, tandis qu'un sommeil adéquat permet d'avoir la force d'étudier et de prier. L'équilibre est fondamental pour le service divin.",
        "practical_example": "Une personne dort 10 heures par nuit en pensant que c'est meilleur pour la santé. Les Sages et médecins considèrent cela néfaste.",
        "common_trap": "Penser que plus on dort, plus on est en forme pour servir Dieu, ou inversement, se priver totalement de sommeil au détriment de sa santé.",
        "importance": "important",
        "frequency": "common",
        "learning_level": 2,
        "knowledge_type": "principle",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 4}],
        "concepts": ["שמירת הגוף", "שינה"]
    },
    {
        "id": "s1-kp-003",
        "title": "Dormir la journée",
        "rule": "Il convient d'éviter de dormir la journée pour ne pas perdre de temps d'étude, sauf si cela permet de mieux étudier la nuit ou le jour de Chabbat.",
        "explanation": "Le temps est précieux et doit être consacré à la Torah. Le sommeil diurne n'est justifié que s'il sert un but spirituel ou s'il s'agit du repos de Chabbat (qui est une Mitsva).",
        "practical_example": "Une personne fait une courte sieste l'après-midi afin de pouvoir rester éveillée pour un cours de Torah le soir.",
        "common_trap": "Prendre l'habitude de dormir la journée par simple paresse.",
        "importance": "important",
        "frequency": "common",
        "learning_level": 2,
        "knowledge_type": "permission",
        "halakha_status": "conditional",
        "sources": [{"siman": 1, "seif": 5}],
        "concepts": ["ביטול תורה", "שינה", "שבת"]
    },
    {
        "id": "s1-kp-004",
        "title": "L'étude nocturne ne doit pas faire rater la prière",
        "rule": "Celui qui étudie tard la nuit doit s'assurer de ne pas rater l'heure de la lecture du Chema et de la prière.",
        "explanation": "L'étude de la Torah est vitale, mais elle ne justifie pas l'annulation ou le retard des Mitsvot obligatoires du matin, dont les horaires sont stricts.",
        "practical_example": "Un étudiant reste éveillé toute la nuit pour étudier, mais s'endort au petit matin et rate l'heure du Chema. Il doit réorganiser son temps.",
        "common_trap": "Croire que le mérite de l'étude de la nuit dispense de se lever à l'heure pour la prière matinale.",
        "importance": "essential",
        "frequency": "common",
        "learning_level": 2,
        "knowledge_type": "priority",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 7}],
        "concepts": ["זמן קריאת שמע", "תפילה", "תלמוד תורה"]
    },
    {
        "id": "s1-kp-005",
        "title": "Se lever sans brusquerie",
        "rule": "Il ne faut pas se tenir debout brusquement juste après le sommeil, car cela peut nuire à la santé. Il faut patienter un peu (ex: s'asseoir sur le lit).",
        "explanation": "La préservation de la santé physique fait partie du service divin. L'empressement (Zrizout) ne doit pas se faire au détriment de la santé corporelle.",
        "practical_example": "Au réveil, une personne s'assoit quelques instants sur son lit pour s'habiller avant de se lever sur ses pieds.",
        "common_trap": "Sauter du lit pour se tenir debout instantanément en pensant accomplir la notion de 'Zrizout' (empressement).",
        "importance": "important",
        "frequency": "common",
        "learning_level": 2,
        "knowledge_type": "practical_case",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 8}],
        "concepts": ["שמירת הגוף", "השכמת הבוקר"]
    },
    {
        "id": "s1-kp-006",
        "title": "Dire Modé Ani au réveil",
        "rule": "Dès son réveil, on témoigne sa foi en récitant le 'Modé Ani', même avant de s'être lavé les mains (Nétilat Yadaïm).",
        "explanation": "Le Modé Ani ne contient pas les Noms saints de Dieu. Par conséquent, il est permis de le réciter même si l'esprit d'impureté réside encore sur les mains.",
        "practical_example": "Une personne ouvre les yeux et récite immédiatement Modé Ani dans son lit, avant même de se lever pour aller faire Nétilat Yadaïm.",
        "common_trap": "Attendre de s'être lavé les mains pour dire Modé Ani.",
        "importance": "essential",
        "frequency": "common",
        "learning_level": 1,
        "knowledge_type": "obligation",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 9}],
        "concepts": ["מודה אני", "טומאה", "אמונה"]
    },
    {
        "id": "s1-kp-007",
        "title": "Consacrer le début de sa journée à Hachem",
        "rule": "La première pensée, parole et action de la journée doivent être orientées vers Dieu et Son service.",
        "explanation": "L'essentiel du jour réside dans son commencement. La manière dont on commence la journée influence tout le reste.",
        "practical_example": "Au lieu de consulter son téléphone au réveil, on pense à la bonté de Dieu, on prononce Modé Ani, et on se prépare pour la prière.",
        "common_trap": "Commencer sa journée par des pensées et actions profanes avant de se tourner vers le service divin.",
        "importance": "essential",
        "frequency": "common",
        "learning_level": 1,
        "knowledge_type": "principle",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 10}],
        "concepts": ["השכמת הבוקר", "עבודת ה'"]
    },
    {
        "id": "s1-kp-008",
        "title": "L'éducation des enfants au lever",
        "rule": "Il est bon d'habituer un enfant qui sait parler à dire Modé Ani et à se laver les mains au réveil.",
        "explanation": "L'éducation religieuse (Hinoukh) commence dès le plus jeune âge, avec des gestes simples et fondamentaux du quotidien.",
        "practical_example": "Des parents apprennent à leur enfant de trois ans à réciter Modé Ani dès qu'il se réveille le matin.",
        "common_trap": "Penser qu'un jeune enfant n'est pas concerné par les lois du lever matinal.",
        "importance": "important",
        "frequency": "common",
        "learning_level": 2,
        "knowledge_type": "custom",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 11}],
        "concepts": ["חינוך", "מודה אני", "נטילת ידיים"]
    },
    {
        "id": "s1-kp-009",
        "title": "Le principe de Shiviti Hachem",
        "rule": "Il faut constamment prendre conscience que Dieu, dont la gloire remplit la terre, se tient au-dessus de nous et voit nos actions.",
        "explanation": "Cette pensée amène naturellement la crainte du Ciel et la soumission, empêchant l'homme de fauter même en privé.",
        "practical_example": "Une personne est seule dans une pièce et s'apprête à faire une action répréhensible. Elle se souvient de 'Shiviti Hachem' et s'en abstient.",
        "common_trap": "Agir différemment en public et en privé, en oubliant que Dieu voit tout.",
        "importance": "essential",
        "frequency": "common",
        "learning_level": 1,
        "knowledge_type": "principle",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 12}],
        "concepts": ["שויתי ה'", "יראת שמים", "השגחה פרטית"]
    },
    {
        "id": "s1-kp-010",
        "title": "Discrétion dans l'accomplissement des Mitsvot",
        "rule": "Il faut dissimuler ses bonnes actions autant que possible et éviter l'ostentation.",
        "explanation": "La récompense d'une Mitsva accomplie en secret est donnée par Dieu Lui-même, tandis qu'une action publique est récompensée par les anges.",
        "practical_example": "Une personne donne la Tsedaka de manière anonyme sans le dire à personne.",
        "common_trap": "Chercher la reconnaissance publique pour les actes de piété.",
        "importance": "essential",
        "frequency": "common",
        "learning_level": 2,
        "knowledge_type": "principle",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 16}],
        "concepts": ["הצנע לכת", "ענווה"]
    },
    {
        "id": "s1-kp-011",
        "title": "Modifier ses paroles par humilité",
        "rule": "Celui qui accomplit une Mitsva peut modifier ses paroles s'il le fait par humilité et pour ne pas paraître orgueilleux.",
        "explanation": "La valeur de la discrétion et de l'humilité prime parfois sur l'exactitude stricte, si l'intention est pure.",
        "practical_example": "Quelqu'un demande à un érudit s'il a terminé l'étude de tout le Talmud. Par humilité, il répond évasivement ou minimise pour éviter l'orgueil.",
        "common_trap": "Se vanter de ses exploits spirituels sous prétexte de 'dire la vérité'.",
        "importance": "advanced",
        "frequency": "occasional",
        "learning_level": 3,
        "knowledge_type": "permission",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 17}],
        "concepts": ["ענווה", "שינוי מפני השלום"]
    },
    {
        "id": "s1-kp-012",
        "title": "Accepter la Mitsva d'aimer son prochain avant la prière",
        "rule": "On a l'habitude d'accepter sur soi la Mitsva 'Tu aimeras ton prochain comme toi-même' avant la prière du matin.",
        "explanation": "L'unité d'Israël permet à la prière de chacun de s'intégrer à l'ensemble des prières de la communauté, ce qui la rend plus facilement acceptée.",
        "practical_example": "Avant de commencer Hodu ou Baroukh Chéamar, on récite la phrase d'acceptation de l'amour du prochain.",
        "common_trap": "Prier avec ferveur tout en gardant rancune envers un autre Juif.",
        "importance": "important",
        "frequency": "common",
        "learning_level": 2,
        "knowledge_type": "custom",
        "halakha_status": "custom",
        "sources": [{"siman": 1, "seif": 19}],
        "concepts": ["ואהבת לרעך כמוך", "תפילה", "אחדות"]
    },
    {
        "id": "s1-kp-013",
        "title": "Qualité (Intention) vs Quantité",
        "rule": "Peu de supplications dites avec intention (Kavana) valent mieux que beaucoup dites sans intention.",
        "explanation": "Le service divin nécessite la présence du cœur. Une prière courte et sincère est plus appréciée qu'une longue prière machinale.",
        "practical_example": "Une personne pressée par le temps choisit de réciter seulement quelques passages des supplications (Ta'hanoun), mais le fait avec concentration.",
        "common_trap": "Vouloir tout lire très vite sans rien comprendre juste pour 'cocher la case'.",
        "importance": "essential",
        "frequency": "common",
        "learning_level": 1,
        "knowledge_type": "principle",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 20}],
        "concepts": ["כוונה בתפילה", "תחנונים"]
    },
    {
        "id": "s1-kp-014",
        "title": "Priorité : Parachat Haakedah vs Psaumes (Chabbat)",
        "rule": "Si on est en retard le Chabbat, il faut sauter les Psaumes supplémentaires du Chabbat plutôt que de sauter la Parachat Haakedah.",
        "explanation": "La lecture de la ligature d'Isaac (Parachat Haakedah) est plus fréquente (dite tous les jours) que les Psaumes spécifiques au Chabbat. Le principe halakhique est 'Tadir Vechééno Tadir, Tadir Kodem' (le plus fréquent précède).",
        "practical_example": "Un homme arrive à la synagogue alors que l'office a déjà commencé. Il choisit de lire la Parachat Haakedah et passe les Psaumes du Chabbat pour rattraper la communauté.",
        "common_trap": "Sauter la Parachat Haakedah sous prétexte qu'on doit lire les prières 'spéciales' de Chabbat.",
        "importance": "advanced",
        "frequency": "occasional",
        "learning_level": 3,
        "knowledge_type": "priority",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 24}],
        "concepts": ["תדיר ושאינו תדיר", "עקידת יצחק", "פסוקי דזמרה"]
    },
    {
        "id": "s1-kp-015",
        "title": "La lecture des sacrifices (Korbanot)",
        "rule": "Il est bon de réciter chaque jour le passage des sacrifices (Parachat Hatamid et Ezehou Mekoman), bien que ce ne soit pas une obligation absolue.",
        "explanation": "Depuis la destruction du Temple, la prière et l'étude des sacrifices remplacent leur offrande. Cela offre également une protection spirituelle.",
        "practical_example": "Une personne prend soin d'arriver tôt à la synagogue pour lire calmement les sacrifices avant l'office.",
        "common_trap": "Négliger systématiquement les sacrifices en pensant que seule la Amida compte.",
        "importance": "important",
        "frequency": "common",
        "learning_level": 2,
        "knowledge_type": "custom",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 26}, {"siman": 1, "seif": 29}],
        "concepts": ["קרבנות", "פרשת התמיד", "איזהו מקומן"]
    },
    {
        "id": "s1-kp-016",
        "title": "Réciter les sacrifices assis (Coutume)",
        "rule": "La coutume est de réciter les passages des sacrifices en étant assis. Il ne faut pas se tenir debout si la communauté est assise, par crainte de paraître orgueilleux (Yohara).",
        "explanation": "Bien que les sacrifices étaient offerts debout, la coutume établie prévaut. Adopter une rigueur ostentatoire en décalage avec la communauté est réprouvé.",
        "practical_example": "Un fidèle lit les sacrifices assis à sa place, comme le reste de la communauté séfarade.",
        "common_trap": "Se lever pour lire les sacrifices afin de montrer sa piété, alors que tous les autres sont assis.",
        "importance": "important",
        "frequency": "common",
        "learning_level": 2,
        "knowledge_type": "custom",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 32}],
        "concepts": ["יוהרא", "קרבנות", "מנהג"]
    },
    {
        "id": "s1-kp-017",
        "title": "Les femmes et les sacrifices",
        "rule": "Les femmes n'ont pas l'obligation de réciter le passage des sacrifices.",
        "explanation": "La récitation des sacrifices n'est pas une obligation absolue, même pour les hommes. Par conséquent, l'usage s'est établi que les femmes ne le font pas en général.",
        "practical_example": "Une femme prie le matin en commençant directement par les bénédictions du matin et Baroukh Chéamar, sans réciter les sacrifices.",
        "common_trap": "Penser qu'une femme manque à ses obligations si elle ne récite pas les sacrifices.",
        "importance": "important",
        "frequency": "common",
        "learning_level": 2,
        "knowledge_type": "permission",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 33}],
        "concepts": ["חיוב נשים", "קרבנות"]
    },
    {
        "id": "s1-kp-018",
        "title": "Heure de récitation des sacrifices",
        "rule": "Les passages des sacrifices ne doivent être récités que de jour, c'est-à-dire à partir de l'aube (Amoud Hacha'har).",
        "explanation": "Dans le Temple, les sacrifices ne pouvaient être offerts que le jour. La prière qui les remplace suit la même règle temporelle.",
        "practical_example": "Quelqu'un se lève très tôt avant l'aube. Il devra attendre le lever de l'aube pour réciter le passage des sacrifices.",
        "common_trap": "Réciter les sacrifices au milieu de la nuit lorsqu'on lit le Tikkoun Hatzot.",
        "importance": "important",
        "frequency": "common",
        "learning_level": 2,
        "knowledge_type": "time",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 35}],
        "concepts": ["זמן קרבנות", "עמוד השחר"]
    },
    {
        "id": "s1-kp-019",
        "title": "Pitoum Haktoret (L'encens)",
        "rule": "Il est bon de réciter la composition de l'encens (Pitoum Haktoret) avec une grande ferveur le matin et à Min'ha.",
        "explanation": "La lecture de l'encens est considérée comme remplaçant l'offrande elle-même, mais on ne dit pas explicitement 'que cela remplace' de peur qu'une erreur de lecture n'équivaille à un encens incomplet (qui était passible de mort).",
        "practical_example": "On lit la liste des 11 épices avec attention dans le Siddour pour ne sauter aucun mot.",
        "common_trap": "Lire le Pitoum Haktoret rapidement de mémoire et omettre involontairement une épice.",
        "importance": "important",
        "frequency": "common",
        "learning_level": 2,
        "knowledge_type": "custom",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 38}, {"siman": 1, "seif": 39}],
        "concepts": ["פיטום הקטורת", "קטורת", "כוונה"]
    },
    {
        "id": "s1-kp-020",
        "title": "Tikkoun 'Hatsot (Le deuil sur le Temple)",
        "rule": "Il convient à toute personne craignant le Ciel de se lamenter à minuit sur la destruction du Temple et l'exil de la Chékhina.",
        "explanation": "Le Tikkoun 'Hatsot exprime le deuil et l'empathie pour la douleur divine. La joie est de mise pour la prière et l'étude, mais la nuit permet de ressentir l'exil.",
        "practical_example": "Une personne se lève à minuit pour réciter le Tikkoun Hatzot, assis par terre avec de la cendre, selon la coutume kabbalistique.",
        "common_trap": "Penser que la religion n'exige que de la joie et négliger l'aspect de deuil pour la destruction du Temple.",
        "importance": "important",
        "frequency": "occasional",
        "learning_level": 3,
        "knowledge_type": "custom",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 43}],
        "concepts": ["תיקון חצות", "חורבן הבית", "גלות"]
    },
    {
        "id": "s1-kp-021",
        "title": "Posture pour le Tikkoun 'Hatsot",
        "rule": "La coutume est de s'asseoir par terre (ou sur un banc bas) pour réciter le Tikkoun Rachel.",
        "explanation": "Cette posture symbolise le deuil. Toutefois, les jours où seul le Tikkoun Léa est récité (qui est composé de louanges), on n'adopte pas cette posture.",
        "practical_example": "On place un tissu ou un coussin fin sur le carrelage et on s'assoit pour réciter le Tikkoun Rachel.",
        "common_trap": "S'asseoir par terre un jour de fête ou de Chabbat, ou pour le Tikkoun Léa seul.",
        "importance": "advanced",
        "frequency": "occasional",
        "learning_level": 3,
        "knowledge_type": "practical_case",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 44}],
        "concepts": ["אבלות", "תיקון חצות", "תיקון רחל"]
    },
    {
        "id": "s1-kp-022",
        "title": "Tikkoun 'Hatsot l'après-midi (Ben HaMetsarim)",
        "rule": "Pendant la période des Trois Semaines (Ben HaMetsarim), il est de coutume de réciter le Tikkoun 'Hatsot après la mi-journée (Hatsot Hayom).",
        "explanation": "Ces semaines étant dédiées au deuil national, la plainte de la destruction du Temple trouve sa place même en pleine journée. Le reste de l'année, ce n'est fait qu'à minuit.",
        "practical_example": "À 13h30 pendant les Trois Semaines, un fidèle s'assoit par terre dans la synagogue pour réciter le Tikkoun Rachel.",
        "common_trap": "Réciter le Tikkoun Hatzot en plein jour au mois de Kislev.",
        "importance": "advanced",
        "frequency": "occasional",
        "learning_level": 3,
        "knowledge_type": "custom",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 45}],
        "concepts": ["בין המצרים", "תיקון חצות"]
    },
    {
        "id": "s1-kp-023",
        "title": "Interdiction de lire des Psaumes avant minuit",
        "rule": "Il ne faut pas lire des Psaumes (Tehilim) ou d'autres textes bibliques la nuit avant le milieu de la nuit ('Hatsot), sauf cas de force majeure.",
        "explanation": "Selon la Kabbale, la première partie de la nuit est sous le signe de la rigueur (Din). L'étude du Talmud ou des lois est permise, mais la lecture des versets simples est déconseillée jusqu'à minuit. Exceptions: Chabbat ou urgences (comme une naissance).",
        "practical_example": "Une personne souhaite lire des Psaumes pour un malade à 21h un soir de semaine. Il est préférable qu'elle étudie la Michna ou attende minuit.",
        "common_trap": "Lire régulièrement des Psaumes avant minuit par méconnaissance.",
        "importance": "advanced",
        "frequency": "occasional",
        "learning_level": 3,
        "knowledge_type": "prohibition",
        "halakha_status": "conditional",
        "sources": [{"siman": 1, "seif": 46}],
        "concepts": ["קריאת תהילים בלילה", "חצות לילה"]
    },
    {
        "id": "s1-kp-024",
        "title": "Différences entre Tikkoun Rachel et Tikkoun Léa",
        "rule": "Le Tikkoun Rachel concerne la destruction et exprime le deuil. Le Tikkoun Léa contient des louanges et des remerciements.",
        "explanation": "C'est la raison pour laquelle le Tikkoun Rachel est omis lors des jours festifs ou à l'approche de réjouissances, tandis que le Tikkoun Léa est souvent maintenu.",
        "practical_example": "La nuit de 'Hanouka, on récite le Tikkoun Léa mais on omet le Tikkoun Rachel, car c'est une fête.",
        "common_trap": "Penser que les deux Tikkounim sont indissociables.",
        "importance": "advanced",
        "frequency": "occasional",
        "learning_level": 3,
        "knowledge_type": "definition",
        "halakha_status": "clear",
        "sources": [{"siman": 1, "seif": 55}],
        "concepts": ["תיקון רחל", "תיקון לאה"]
    },
    {
        "id": "s1-kp-025",
        "title": "Cas de l'endeuillé (Tikkoun 'Hatsot)",
        "rule": "Dans une maison de deuil, on ne récite pas le Tikkun Rachel, mais uniquement le Tikkun Léa (selon le premier avis).",
        "explanation": "La douleur personnelle de l'endeuillé ne doit pas se superposer de cette façon, et un autre avis le dispense d'ailleurs des deux.",
        "practical_example": "Un homme en période de Chiva récite le Tikkun Léa la nuit, mais saute le Tikkun Rachel.",
        "common_trap": "Obliger un endeuillé à dire le Tikkun Rachel comme tout le monde.",
        "importance": "advanced",
        "frequency": "rare",
        "learning_level": 4,
        "knowledge_type": "exception",
        "halakha_status": "dispute",
        "sources": [{"siman": 1, "seif": 59}],
        "concepts": ["אבלות", "תיקון חצות"]
    }
]

file_content = json.dumps(knowledge_points, indent=2, ensure_ascii=False)

with open(r"c:\Users\natha\OneDrive\Bureau\My Apps\Halakh'App\public\data\הלכות הנהגת אדם בבוקר\siman_1_knowledge.json", 'w', encoding='utf-8') as f:
    f.write(file_content)
